In [1]:
import pandas as pd
import numpy as np

path = r'C:\Users\mariu\Documents\Project Local Elections/bm_ka_stut.csv'
data_ob = pd.read_csv(path, sep=';')

In [2]:
list_supporters = data_ob['support'].astype(str).str.split(',', expand=True)[0].unique()

for i in range(len(list_supporters)):
    
    name = list_supporters[i] + '_support'
    data_ob.loc[data_ob['support'].str.contains(list_supporters[i], regex=False, na=False), name] = 1
    
    data_ob[name] = data_ob[name].fillna(0)

data_ob.head()

candidate  party    votes percent    year       city  runoff  \
0   Ingo Wellenreuther     CDU   32.430   35,40  2012.0  Karlsruhe     0.0   
1  Friedemann Kalmbach     GfK    4.090    4,46  2012.0  Karlsruhe     0.0   
2     Sascha Toni Oehme    NaN  363.000    0,40  2012.0  Karlsruhe     0.0   
3        Frank Mentrup     SPD   50.615   55,25  2012.0  Karlsruhe     0.0   
4   Niko Fostiropoulos   Linke    2.164    2,36  2012.0  Karlsruhe     0.0   

                    support              job year_birth  ...  GRÜNE_support  \
0                       CDU              MdB       1959  ...            0.0   
1                       GfK           Lehrer       1953  ...            0.0   
2                       NaN  Logistikmeister       1963  ...            0.0   
3  SPD, GRÜNE, Piraten, KAL              MdL       1964  ...            1.0   
4                     Linke        Architekt       1958  ...            0.0   

  BüKa_support  KAL_support  FDP_support  Piraten_support  BüSo_support  \
0          0.0          0.0          0.0              0.0           0.0   
1          0.0          0.0          0.0              0.0           0.0   
2          0.0          0.0          0.0              0.0           0.0   
3          0.0          1.0          0.0              1.0           0.0   
4          0.0          0.0          0.0              0.0           0.0   

   Partei_support PBC_support AfD_support Grüne_support  
0             0.0         0.0         0.0           0.0  
1             0.0         0.0         0.0           0.0  
2             0.0         0.0         0.0           0.0  
3             0.0         0.0         0.0           0.0  
4             0.0         0.0         0.0           0.0  

[5 rows x 67 columns]

In [3]:
to_float = ['percent', 'area_industry_pc', 'area_agricul_pc', 'area_forest_pc', 'workers_agricul', 'workers_manu', 'workers_service', 'btw_erststimme_pc']
for z in range(len(to_float)):
    data_ob[to_float[z]] = data_ob[to_float[z]].str.replace(',', '.')
    data_ob[to_float[z]] = data_ob[to_float[z]].astype(float)/100
    
data_ob['age'] = 2020 - data_ob['year_birth'].astype(float)
data_ob = data_ob.rename({'Unnamed:11': 'City_of_birth', 'male':'male_candidate'})
data_ob['visits_total'] = data_ob['visits_total'].str.replace('.','').astype(float)/data_ob['population']
data_ob['visits_foreigner'] = data_ob['visits_foreigner'].str.replace('.', '').astype(float)/data_ob['population']
data_ob['feinstaub'] = data_ob['feinstaub'].str.replace(',', '.').astype(float)/data_ob['population']

to_share = ['male', 'female', 'unter 15', '15-18', '18-25', '25-40', '40-65', '65 u.mehr', 'visits_total', 'visits_foreigner', 'feinstaub', 'workers_agricul', 'workers_manu', 'workers_service',
           'unemployed', 'health_care_receivers', 'asylum_claims']
for u in range(len(to_share)):
    data_ob[to_share[u]] = data_ob[to_share[u]]/data_ob['population']

for column in range(len(data_ob.columns[data_ob.columns.str.contains('kom_wahl')])):
    column_now = data_ob.columns[data_ob.columns.str.contains('kom_wahl')][column]
    data_ob[column_now] = data_ob[column_now].str.replace(',', '.')
    data_ob[column_now] = data_ob[column_now].astype(float)/100

data_ob['size_new_flat'] = data_ob['new_flat_sqm_allowed']*1000/data_ob['numb_new_flat_allowed']
data_ob

candidate   party    votes  percent    year       city  runoff  \
0    Ingo Wellenreuther      CDU   32.430   0.3540  2012.0  Karlsruhe     0.0   
1   Friedemann Kalmbach      GfK    4.090   0.0446  2012.0  Karlsruhe     0.0   
2      Sascha Toni Oehme     NaN  363.000   0.0040  2012.0  Karlsruhe     0.0   
3         Frank Mentrup      SPD   50.615   0.5525  2012.0  Karlsruhe     0.0   
4    Niko Fostiropoulos    Linke    2.164   0.0236  2012.0  Karlsruhe     0.0   
..                   ...     ...      ...      ...     ...        ...     ...   
75            Sven Weigt     CDU      NaN      NaN  2020.0  Karlsruhe     0.0   
76          Petra Lorenz      FW      NaN      NaN  2020.0  Karlsruhe     0.0   
77      Dr. Paul Schmidt     AfD      NaN      NaN  2020.0  Karlsruhe     0.0   
78        Vanessa Schulz  Partei      NaN      NaN  2020.0  Karlsruhe     0.0   
79                   NaN     NaN      NaN      NaN     NaN        NaN     NaN   

                     support                 job year_birth  ...  KAL_support  \
0                        CDU                 MdB       1959  ...          0.0   
1                        GfK              Lehrer       1953  ...          0.0   
2                        NaN     Logistikmeister       1963  ...          0.0   
3   SPD, GRÜNE, Piraten, KAL                 MdL       1964  ...          1.0   
4                      Linke           Architekt       1958  ...          0.0   
..                       ...                 ...        ...  ...          ...   
75                  CDU, FDP       Bürgermeister       1971  ...          0.0   
76                FW, Für KA       Unternehmerin       1967  ...          0.0   
77                       AfD            Physiker       1966  ...          0.0   
78                    Partei  Projektassistentin       1981  ...          0.0   
79                       NaN                 NaN        NaN  ...          0.0   

   FDP_support  Piraten_support  BüSo_support  Partei_support  PBC_support  \
0          0.0              0.0           0.0             0.0          0.0   
1          0.0              0.0           0.0             0.0          0.0   
2          0.0              0.0           0.0             0.0          0.0   
3          0.0              1.0           0.0             0.0          0.0   
4          0.0              0.0           0.0             0.0          0.0   
..         ...              ...           ...             ...          ...   
75         1.0              0.0           0.0             0.0          0.0   
76         0.0              0.0           0.0             0.0          0.0   
77         0.0              0.0           0.0             0.0          0.0   
78         0.0              0.0           0.0             1.0          0.0   
79         0.0              0.0           0.0             0.0          0.0   

    AfD_support  Grüne_support   age  size_new_flat  
0           0.0            0.0  61.0      90.729391  
1           0.0            0.0  67.0      90.729391  
2           0.0            0.0  57.0      90.729391  
3           0.0            0.0  56.0      90.729391  
4           0.0            0.0  62.0      90.729391  
..          ...            ...   ...            ...  
75          0.0            0.0  49.0      94.270428  
76          0.0            0.0  53.0      94.270428  
77          1.0            0.0  54.0      94.270428  
78          0.0            0.0  39.0      94.270428  
79          0.0            0.0   NaN            NaN  

[80 rows x 69 columns]

In [4]:
data_background_name = pd.get_dummies(data_ob['lastname_background_density'])
data_ob = pd.concat([data_ob, data_background_name], axis=1)
data_ob.head()

candidate  party    votes  percent    year       city  runoff  \
0   Ingo Wellenreuther     CDU   32.430   0.3540  2012.0  Karlsruhe     0.0   
1  Friedemann Kalmbach     GfK    4.090   0.0446  2012.0  Karlsruhe     0.0   
2     Sascha Toni Oehme    NaN  363.000   0.0040  2012.0  Karlsruhe     0.0   
3        Frank Mentrup     SPD   50.615   0.5525  2012.0  Karlsruhe     0.0   
4   Niko Fostiropoulos   Linke    2.164   0.0236  2012.0  Karlsruhe     0.0   

                    support              job year_birth  ...  Denmark Germany  \
0                       CDU              MdB       1959  ...        0       1   
1                       GfK           Lehrer       1953  ...        0       1   
2                       NaN  Logistikmeister       1963  ...        0       1   
3  SPD, GRÜNE, Piraten, KAL              MdL       1964  ...        0       1   
4                     Linke        Architekt       1958  ...        0       0   

   Ghana  Greece  Jamaica  Liechtenstein  Luxembourg  Switzerland  UK  \
0      0       0        0              0           0            0   0   
1      0       0        0              0           0            0   0   
2      0       0        0              0           0            0   0   
3      0       0        0              0           0            0   0   
4      0       1        0              0           0            0   0   

   United States  
0              0  
1              0  
2              0  
3              0  
4              0  

[5 rows x 81 columns]

In [5]:
data_ob['job'].unique()
politician = ['MdB', 'MdL', 'OB', 'Bürgermeister', 'Bürgermeisterin', 'Oberbürgermeister', 'Staatsrätin']
business = ['Unternehmerin', 'IT-Unternehmer', 'Medienunternehmer', 'Unternehmer', 'Geschäftsführer', 'Managerin', 'Unternehmensberater']
educ_soc = ['Lehrer', 'Künstler', 'Travestiekünstler\xa0', 'Journalist', 'Gastronom']
laborer = ['Kaufmann', 'Betriebsrat', 'Buchdrucker', 'Drucker', 'EDV-Techniker', 'Industriekaufmann', 'Projektassistentin', 'Logistikmeister']

name_lists = ['politician', 'business', 'educ_soc', 'laborer']
list_of_lists = [politician, business, educ_soc, laborer]

for j in range(len(list_of_lists)):
    list_now = list_of_lists[j]
    for i in range(len(list_now)):
        name = 'job_' + name_lists[j]
        data_ob.loc[data_ob['job'].str.contains(list_now[i], regex=False, na=False), name] = 1
        data_ob[name] = data_ob[name].fillna(0)
        
data_ob.head()

candidate  party    votes  percent    year       city  runoff  \
0   Ingo Wellenreuther     CDU   32.430   0.3540  2012.0  Karlsruhe     0.0   
1  Friedemann Kalmbach     GfK    4.090   0.0446  2012.0  Karlsruhe     0.0   
2     Sascha Toni Oehme    NaN  363.000   0.0040  2012.0  Karlsruhe     0.0   
3        Frank Mentrup     SPD   50.615   0.5525  2012.0  Karlsruhe     0.0   
4   Niko Fostiropoulos   Linke    2.164   0.0236  2012.0  Karlsruhe     0.0   

                    support              job year_birth  ...  Jamaica  \
0                       CDU              MdB       1959  ...        0   
1                       GfK           Lehrer       1953  ...        0   
2                       NaN  Logistikmeister       1963  ...        0   
3  SPD, GRÜNE, Piraten, KAL              MdL       1964  ...        0   
4                     Linke        Architekt       1958  ...        0   

  Liechtenstein  Luxembourg  Switzerland  UK  United States  job_politician  \
0             0           0            0   0              0             1.0   
1             0           0            0   0              0             0.0   
2             0           0            0   0              0             0.0   
3             0           0            0   0              0             1.0   
4             0           0            0   0              0             0.0   

   job_business  job_educ_soc  job_laborer  
0           0.0           0.0          0.0  
1           0.0           1.0          0.0  
2           0.0           0.0          1.0  
3           0.0           0.0          0.0  
4           0.0           0.0          0.0  

[5 rows x 85 columns]

In [6]:
# groupby count: candidate, incumbent, runoff (here, number of candidates/incumbents matters)
# groupby mean: 'population', 'pop_density', 'area_industry_pc', 'area_agricul_pc', 'area_forest_pc', 'female', 'unter 15', '15-18', '18-25', '25-40', '40-65', '65 u.mehr', 'male.1', 
# 'workers_agricul', 'workers_manu', 'workers_service', 'unemployed', 'health_care_receivers', 'asylum_claims', 'disp_income', 'investment_p_worker', 'numb_new_flat_allowed', 'new_flat_sqm_allowed', 
# 'visits_total', 'visits_foreigner', 'feinstaub', 
# Strategy group by election (e.g. year and city)

data_ob_runoff_0 = data_ob.groupby(['city', 'year'], as_index=False).count()['candidate']
data_ob_runoff_1 = data_ob.groupby(['city', 'year'], as_index=False).sum()[['city', 'year','runoff', 'incumbent']]
data_ob_runoff_2 = data_ob.groupby(['city', 'year'], as_index=False).mean()[['population', 'pop_density', 'area_industry_pc', 'area_agricul_pc', 'area_forest_pc', 'female', 'unter 15', '15-18', '18-25', 
                                                                             '25-40', '40-65', '65 u.mehr', 'male.1','workers_agricul', 'workers_manu', 'workers_service', 'unemployed', 
                                                                             'health_care_receivers', 'asylum_claims', 'disp_income', 'investment_p_worker', 'numb_new_flat_allowed', 'new_flat_sqm_allowed', 
                                                                             'visits_total', 'visits_foreigner', 'feinstaub']]
data_ob_runoff = pd.concat([data_ob_runoff_1, data_ob_runoff_0, data_ob_runoff_2], axis=1)

data_ob_runoff.loc[data_ob_runoff['runoff'] > 0, 'runoff'] =1
data_ob_runoff

city    year  runoff  incumbent  candidate  population  pop_density  \
0  Karlsruhe  1998.0     1.0        1.0         15     276.536        1.594   
1  Karlsruhe  2006.0     0.0        1.0          7     286.327        1.651   
2  Karlsruhe  2012.0     0.0        0.0          7     296.033        1.707   
3  Karlsruhe  2020.0     0.0        1.0          5     312.060        1.799   
4  Stuttgart  2004.0     1.0        1.0          9     590.657        2.849   
5  Stuttgart  2012.0     1.0        0.0         22     597.939        2.884   
6  Stuttgart  2020.0     0.0        0.0         14     635.911        3.067   

   area_industry_pc  area_agricul_pc  area_forest_pc  ...  unemployed  \
0             0.096            0.243           0.259  ...    0.034737   
1             0.098            0.244           0.259  ...    0.043621   
2             0.099            0.227           0.257  ...    0.028453   
3             0.100            0.226           0.256  ...    0.021070   
4             0.075            0.240           0.235  ...    0.036652   
5             0.076            0.229           0.235  ...    0.027804   
6             0.075            0.227           0.235  ...    0.022014   

   health_care_receivers  asylum_claims  disp_income  investment_p_worker  \
0               0.025610       0.694304        5.533                7.436   
1               0.025768       0.523877        6.830                7.749   
2               0.026723       0.449274        7.803                8.565   
3               0.027786       3.060309        9.120                8.861   
4               0.017619       0.002164       14.950               14.074   
5               0.021705       1.429912       18.348               21.377   
6               0.023420       0.004420       21.933               28.255   

   numb_new_flat_allowed  new_flat_sqm_allowed  visits_total  \
0                912.000                85.860      7.287855   
1                948.000                94.104      9.800355   
2                558.000                50.627     11.483287   
3                514.000                48.455     11.800821   
4                  1.607               147.710      6.435126   
5                  1.316               120.498      8.714678   
6                  1.637               137.007     10.105976   

   visits_foreigner  feinstaub  
0          1.683057   0.002308  
1          2.123510   0.001781  
2          2.892742   0.001151  
3          2.749353   0.000682  
4          1.815179   0.000791  
5          2.494334   0.000520  
6          3.137878   0.000283  

[7 rows x 31 columns]

In [7]:
data_stuttgart = data_ob[data_ob['city'] == 'Stuttgart']
data_karlsruhe = data_ob[data_ob['city'] == 'Karlsruhe']

In [8]:
from sklearn.linear_model import Lasso, SGDClassifier, LogisticRegression # unsure about logreg performance given the case that p > n, omit lasso(lin.reg.)?
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier, VotingClassifier # likely to perform better since averaging, bagging and other ensemble methods push away from estimation boundaries (0,1) since variance needed to be ~= 0
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB # for poll based forecast
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.ensemble import StackingClassifier

scaler = StandardScaler()

In [48]:
data_ob_runoff_train = data_ob_runoff[data_ob_runoff['year'] != 2020]
data_ob_runoff_test = data_ob_runoff[data_ob_runoff['year'] == 2020]

X_runoff_var = ['population', 'pop_density', 'area_industry_pc', 'area_agricul_pc', 'area_forest_pc', 'female', 'unter 15', '15-18', '18-25', '25-40', '40-65', '65 u.mehr', 'male.1','workers_agricul', 
                'workers_manu', 'workers_service', 'unemployed', 'health_care_receivers', 'asylum_claims', 'disp_income', 'investment_p_worker', 'numb_new_flat_allowed', 'new_flat_sqm_allowed', 
                'visits_total', 'visits_foreigner', 'feinstaub']
y_runoff_var = ['runoff']

X_runoff_train = data_ob_runoff_train[X_runoff_var]
X_runoff_test = data_ob_runoff_test[X_runoff_var]
y_runoff_train = data_ob_runoff_train[y_runoff_var]

In [10]:
X_runoff_train.columns[X_runoff_train.isna().any()].tolist(), X_runoff_train.columns[np.isfinite(X_runoff_train).any() == False].tolist(), X_runoff_test.columns[X_runoff_test.isna().any()].tolist(), X_runoff_test.columns[np.isfinite(X_runoff_test).any() == False].tolist()

([], [], [], [])

In [11]:
y_runoff_train.columns[y_runoff_train.isna().any()].tolist(), y_runoff_train.columns[np.isfinite(y_runoff_train).any() == False].tolist()

([], [])

In [57]:
X_runoff_train = scaler.fit_transform(X_runoff_train)
X_runoff_test = scaler.transform(X_runoff_test)


city    year  runoff  incumbent  candidate  population  pop_density  \
3  Karlsruhe  2020.0     0.0        1.0          5     312.060        1.799   
6  Stuttgart  2020.0     0.0        0.0         14     635.911        3.067   

   area_industry_pc  area_agricul_pc  area_forest_pc  ...  unemployed  \
3             0.100            0.226           0.256  ...    0.021070   
6             0.075            0.227           0.235  ...    0.022014   

   health_care_receivers  asylum_claims  disp_income  investment_p_worker  \
3               0.027786       3.060309        9.120                8.861   
6               0.023420       0.004420       21.933               28.255   

   numb_new_flat_allowed  new_flat_sqm_allowed  visits_total  \
3                514.000                48.455     11.800821   
6                  1.637               137.007     10.105976   

   visits_foreigner  feinstaub  
3          2.749353   0.000682  
6          3.137878   0.000283  

[2 rows x 31 columns]

In [65]:
param_grid_log_reg = {'C': np.logspace(0.1, 2, 10, endpoint=True), 'max_iter': np.logspace(1, 5, 10, endpoint=True)}
log_reg_cv = GridSearchCV(estimator = LogisticRegression(), param_grid = param_grid_log_reg, cv = 2, verbose = 2, n_jobs=-1, scoring = 'f1', return_train_score=True)
log_reg_cv.fit(X_runoff_train, y_runoff_train)
log_reg_cv.best_params_, log_reg_cv.score(X_runoff_train, y_runoff_train)

Fitting 2 folds for each of 100 candidates, totalling 200 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done 200 out of 200 | elapsed:    0.5s finished
C:\Users\mariu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\mariu\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


({'C': 1.2589254117941673, 'max_iter': 10.0}, 1.0)

In [76]:
# Define estimator
log_reg = LogisticRegression(C= 1.2589254117941673, max_iter= 100.0)
log_reg.fit(X_runoff_train, y_runoff_train)
log_reg.predict(X_runoff_test)

C:\Users\mariu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


array([1., 1.])

In [15]:
param_grid_sgd = {'alpha': np.logspace(-5, 2, 10, endpoint=True), 'max_iter': np.logspace(1, 4, 10, endpoint=True)}
sgd_cv = GridSearchCV(estimator = SGDClassifier(), param_grid = param_grid_sgd, cv = 2, verbose = 2, n_jobs=-1, scoring = 'f1', return_train_score=True)
sgd_cv.fit(X_runoff_train, y_runoff_train)
sgd_cv.best_params_, sgd_cv.score(X_runoff_train, y_runoff_train)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.


Fitting 2 folds for each of 100 candidates, totalling 200 fits


[Parallel(n_jobs=-1)]: Done 200 out of 200 | elapsed:    0.3s finished
C:\Users\mariu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


({'alpha': 1e-05, 'max_iter': 100.0}, 1.0)

In [55]:
# Define estimator
sgd = SGDClassifier(alpha= 1e-05, max_iter= 46.41588833612777)
sgd.fit(X_runoff_train, y_runoff_train)
sgd.predict(X_runoff_test)

C:\Users\mariu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


array([0., 1.])

In [17]:
param_grid_svc = {'C': np.logspace(-3, 3, 15, endpoint=True)}
svc_cv = GridSearchCV(estimator = SVC(), param_grid = param_grid_svc, cv = 2, verbose = 2, n_jobs=-1, scoring = 'f1', return_train_score=True)
svc_cv.fit(X_runoff_train, y_runoff_train)
svc_cv.best_params_, svc_cv.score(X_runoff_train, y_runoff_train)

Fitting 2 folds for each of 15 candidates, totalling 30 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  15 out of  30 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done  30 out of  30 | elapsed:    0.0s finished
C:\Users\mariu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


({'C': 0.001}, 0.7499999999999999)

In [53]:
# Define estimator
svc = SVC(C= 0.001)
svc.fit(X_runoff_train, y_runoff_train)
svc.predict(X_runoff_test)

C:\Users\mariu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


array([1., 1.])

In [19]:
param_grid_knnc = {'n_neighbors': range(1,2,1), 'weights':['distance', 'uniform']}
knnc_cv = GridSearchCV(estimator = KNeighborsClassifier(), param_grid = param_grid_knnc, cv = 2, verbose = 2, scoring = 'f1', n_jobs=-1, return_train_score=True)
knnc_cv.fit(X_runoff_train, y_runoff_train)
knnc_cv.best_params_, knnc_cv.score(X_runoff_train, y_runoff_train)

Fitting 2 folds for each of 2 candidates, totalling 4 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   4 out of   4 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   4 out of   4 | elapsed:    0.0s finished
C:\Users\mariu\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:765: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


({'n_neighbors': 1, 'weights': 'distance'}, 1.0)

In [52]:
# Define estimator
knnc = KNeighborsClassifier(n_neighbors= 1, weights= 'distance')
knnc.fit(X_runoff_train, y_runoff_train)
knnc.predict(X_runoff_test)

C:\Users\mariu\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


array([0., 1.])

In [21]:
param_grid_rfc = {'n_estimators': range(1,500,10), 'max_depth': range(1,30,6), 'min_samples_split': range(2,30,6), 'min_samples_leaf': range(1,30,6)}
rfc_cv = GridSearchCV(estimator = RandomForestClassifier(), param_grid = param_grid_rfc, cv = 2, verbose = 2, scoring = 'f1', n_jobs=-1, return_train_score=True)
rfc_cv.fit(X_runoff_train, y_runoff_train)
rfc_cv.best_params_, rfc_cv.score(X_runoff_train, y_runoff_train)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.


Fitting 2 folds for each of 6250 candidates, totalling 12500 fits


[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    1.7s
[Parallel(n_jobs=-1)]: Done 178 tasks      | elapsed:   16.1s
[Parallel(n_jobs=-1)]: Done 381 tasks      | elapsed:   35.7s
[Parallel(n_jobs=-1)]: Done 664 tasks      | elapsed:  1.0min
[Parallel(n_jobs=-1)]: Done 1029 tasks      | elapsed:  1.6min
[Parallel(n_jobs=-1)]: Done 1474 tasks      | elapsed:  2.4min
[Parallel(n_jobs=-1)]: Done 2001 tasks      | elapsed:  3.4min
[Parallel(n_jobs=-1)]: Done 2608 tasks      | elapsed:  4.5min
[Parallel(n_jobs=-1)]: Done 3297 tasks      | elapsed:  5.9min
[Parallel(n_jobs=-1)]: Done 4066 tasks      | elapsed:  7.4min
[Parallel(n_jobs=-1)]: Done 4917 tasks      | elapsed:  9.1min
[Parallel(n_jobs=-1)]: Done 5848 tasks      | elapsed: 10.9min
[Parallel(n_jobs=-1)]: Done 6861 tasks      | elapsed: 12.9min
[Parallel(n_jobs=-1)]: Done 7954 tasks      | elapsed: 15.1min
[Parallel(n_jobs=-1)]: Done 9129 tasks      | elapsed: 17.4min
[Parallel(n_jobs=-1)]: Done 10384 tasks      | elapsed: 19.

({'max_depth': 1,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'n_estimators': 21},
 1.0)

In [51]:
rfc = RandomForestClassifier(max_depth= 1,min_samples_leaf= 1,min_samples_split= 2,n_estimators= 21)
rfc.fit(X_runoff_train, y_runoff_train)
rfc.predict(X_runoff_test)

C:\Users\mariu\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


array([0., 1.])

In [22]:
param_grid_ada = {'n_estimators': range(1,500,15), 'learning_rate': np.logspace(-3, 3, 15, endpoint=True)}
ada_cv = GridSearchCV(estimator = AdaBoostClassifier(), param_grid = param_grid_ada, cv = 2, verbose = 2, scoring = 'f1', n_jobs=-1, return_train_score=True)
ada_cv.fit(X_runoff_train, y_runoff_train)
ada_cv.best_params_, ada_cv.score(X_runoff_train, y_runoff_train)

Fitting 2 folds for each of 510 candidates, totalling 1020 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    0.2s
[Parallel(n_jobs=-1)]: Done 1020 out of 1020 | elapsed:    2.0s finished
C:\Users\mariu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


({'learning_rate': 0.0071968567300115215, 'n_estimators': 391}, 1.0)

In [50]:
ada = AdaBoostClassifier(learning_rate= 0.0026826957952797246, n_estimators= 1)
ada.fit(X_runoff_train, y_runoff_train)
ada.predict(X_runoff_test)

C:\Users\mariu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


array([1., 1.])

In [25]:
param_grid_gbc = {'n_estimators': range(1,500,15), 'max_depth':range(1,18,4), 'min_samples_split':range(200,1001,100), 'min_samples_leaf': range(10, 200, 30)}
gbc_cv = GridSearchCV(estimator = GradientBoostingClassifier(), param_grid = param_grid_gbc, cv = 2, verbose = 2, scoring = 'f1', n_jobs=-1, return_train_score=True)
gbc_cv.fit(X_runoff_train, y_runoff_train)
gbc_cv.best_params_, gbc_cv.score(X_runoff_train, y_runoff_train)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.


Fitting 2 folds for each of 10710 candidates, totalling 21420 fits


[Parallel(n_jobs=-1)]: Done  52 tasks      | elapsed:    1.2s
[Parallel(n_jobs=-1)]: Done 536 tasks      | elapsed:   12.7s
[Parallel(n_jobs=-1)]: Done 1348 tasks      | elapsed:   31.9s
[Parallel(n_jobs=-1)]: Done 2480 tasks      | elapsed:   58.6s
[Parallel(n_jobs=-1)]: Done 3940 tasks      | elapsed:  1.5min
[Parallel(n_jobs=-1)]: Done 5720 tasks      | elapsed:  2.2min
[Parallel(n_jobs=-1)]: Done 7828 tasks      | elapsed:  3.0min
[Parallel(n_jobs=-1)]: Done 10256 tasks      | elapsed:  3.9min
[Parallel(n_jobs=-1)]: Done 13012 tasks      | elapsed:  4.9min
[Parallel(n_jobs=-1)]: Done 16088 tasks      | elapsed:  6.0min
[Parallel(n_jobs=-1)]: Done 19492 tasks      | elapsed:  7.3min
[Parallel(n_jobs=-1)]: Done 21420 out of 21420 | elapsed:  8.0min finished
C:\Users\mariu\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change

({'max_depth': 1,
  'min_samples_leaf': 10,
  'min_samples_split': 200,
  'n_estimators': 1},
 0.7499999999999999)

In [49]:
gbc = GradientBoostingClassifier(max_depth=1, min_samples_leaf= 10,  min_samples_split= 200,  n_estimators= 1)
gbc.fit(X_runoff_train, y_runoff_train)
gbc.predict(X_runoff_test)

C:\Users\mariu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


array([1., 1.])

In [77]:
def combinations_on_off(num_classifiers):
    return [[int(x) for x in list("{0:0b}".format(i).zfill(num_classifiers))]
            for i in range(1, 2 ** num_classifiers)]

param_grid = {'weights':combinations_on_off(7)}
estimator = VotingClassifier(estimators=[('rfc', rfc),('ada', ada),('sgd', sgd),('knnc', knnc),('gbc', gbc),('svc', svc),('logr',log_reg)], voting='hard')
ensemble_cv = GridSearchCV(estimator = estimator, param_grid = param_grid , cv=2, n_jobs = 4, verbose = 10,scoring='f1')
ensemble_cv.fit(X_runoff_train, y_runoff_train)
ensemble_cv.best_params_, ensemble_cv.score(X_runoff_train, y_runoff_train)

Fitting 2 folds for each of 127 candidates, totalling 254 fits


[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Batch computation too fast (0.1087s.) Setting batch_size=2.
[Parallel(n_jobs=4)]: Done   5 tasks      | elapsed:    0.1s
[Parallel(n_jobs=4)]: Batch computation too fast (0.1865s.) Setting batch_size=4.
[Parallel(n_jobs=4)]: Done  12 tasks      | elapsed:    0.3s
[Parallel(n_jobs=4)]: Done  28 tasks      | elapsed:    0.6s
[Parallel(n_jobs=4)]: Done  56 tasks      | elapsed:    1.0s
[Parallel(n_jobs=4)]: Done  92 tasks      | elapsed:    1.6s
[Parallel(n_jobs=4)]: Done 128 tasks      | elapsed:    2.2s
[Parallel(n_jobs=4)]: Done 172 tasks      | elapsed:    2.8s
[Parallel(n_jobs=4)]: Done 216 tasks      | elapsed:    3.5s
[Parallel(n_jobs=4)]: Done 254 out of 254 | elapsed:    4.0s finished
C:\Users\mariu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ),

({'weights': [0, 1, 1, 1, 0, 0, 0]}, 1.0)

In [78]:
voting_c = VotingClassifier(estimators=[('rfc', rfc),('ada', ada),('sgd', sgd),('knnc', knnc),('gbc', gbc),('svc', svc),('logr',log_reg)], voting='hard', weights=[0, 1, 1, 1, 0, 0, 0])
voting_c.fit(X_runoff_train, y_runoff_train)
voting_c.predict(X_runoff_test)

C:\Users\mariu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


array([0., 1.])

## Take away für unsere Vorhersage einer Stichwahl in Karlsruhe und Stuttgart:

**Stichwahl in Stuttgart:** <br>
Log: Ja <br>
KNN: Ja <br>
SGD: Ja<br>
ADA: Ja<br>
GB: Ja<br>
VOT: Ja<br>
RF: Ja<br>
SVC: Ja<br>
$\rightarrow$ W'keit  $ 	>99\%$, dass es in eine Stichwahl geht <br>
**Stichwahl in Karlsruhe:** <br>
Log: Ja <br>
KNN: Nein <br>
SGD: Nein<br>
ADA: Ja<br>
GB: Ja<br>
VOT: Nein<br>
RF: Nein<br>
SVC: Ja<br>
$\rightarrow$ W'keit  $ 	\approx50\%$, dass es in eine Stichwahl geht

In [86]:
data_stuttgart.isna().any().to_list()

[False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]